language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

env:
  global:
    - OMP_NUM_THREADS=4
    - LINUX_DIST=bionic

before_install:
  - sudo apt-get update -yqq
install:
  - sudo apt install -yqq libtbb-dev
  - sudo apt -yqq install libgeos-dev
  - pip install --no-cache-dir cython wheel
  - pip install --no-cache-dir shapely==1.8a1 --no-binary shapely
  - pip install --no-cache-dir pygeos --no-binary pygeos
  - pip install --no-cache-dir -r requirements_test.txt
  - python setup.py install
  - cmake . --target capi_test
  - make
script:
  - ./capi_test
  - python run_tests.py