language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

env:
  global:
    - OMP_NUM_THREADS=4
    - LINUX_DIST=bionic

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -yqq
install:
  - sudo apt install -yqq gcc-9 g++-9
  - export CC=gcc-9
  - export CXX=g++-9
  - sudo apt install -yqq libtbb-dev
  - sudo apt -yqq install libgeos-dev
  - pip install --no-cache-dir cython wheel
  - pip install --no-cache-dir shapely==1.8a1 --no-binary shapely
  - pip install --no-cache-dir pygeos --no-binary pygeos
  - pip install --no-cache-dir -r requirements_test.txt
  - python setup.py install
script:
  - ls
  - python run_tests.py