language: python
python:
- '3.7'
- '3.8'
- '3.9'
env:
  global:
  - OMP_NUM_THREADS=4
  - LINUX_DIST=bionic
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -yqq
install:
- sudo apt install -yqq gcc-9 g++-9
- export CC=gcc-9
- export CXX=g++-9
- sudo apt install -yqq libtbb-dev
- sudo apt -yqq install libgeos-dev
- pip install --no-cache-dir cython wheel
- pip install --no-cache-dir shapely==1.8a1 --no-binary shapely
- pip install --no-cache-dir pygeos --no-binary pygeos
- pip install --no-cache-dir -r requirements_test.txt
- cmake .
- make
- cp _vis_graph.*.so capi/src/implementation/visibility_graphs/
script:
- "./capi_test"
- python run_tests.py
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: v7no+Ict2STYkeKCzHVQRdHYv56M1tLFisiGvVjbFBbrP4xc+aVqWov/bDy8hLpZbXL2eudEaGoypZZeTxQL/EX54m2kWqFQppuLaMSHI0nG2nhm5Ofvy06UdpX9InwJUZc2LeK7l6DwjBAWRES66mS89E/hV3RqTCXh0Xv3mVcfHV/CZwAt68GaXF1y7YFPHhbXEcqplqBK9v4ak6YlXaXAax2yLJrt2KQDbw8b4tMIxw4xivXEBBYzheda66ZzrNkU8tgIAYYZMqN14FgB8vzaR1f8boAjXpV+Te8pJ9PcIWrdh2MuH5Q/lrYS9IxtnRLQuTBwa8tnbvhm3a+F9w8lZgk/SQf/gZ0pO49k9kTrPhQPLkGUh0+SAIUgXFcEx6SaHUgWCnCZUaea/dyNdel99tLKRZJ93ltEN954JsydWhGgcO7+ElrxbwgzHytI5gnUQw0dYldeiSel2yv1K1MtmGJnPeVKDpWCwoy7OCynvTBPeRyZzkJr/H/tLKCky6r8pHhg9jf7w2cIk5ioUA6ts/8dYryHJo6A6czbY5G8UdnCX8/4DSyYBRuO7/YpSNRDz7Fi5apfnYH4sMOFawYEbrgxCKyvHRg/FN0M5cZJN2m/RQ7wMlBtAwd5AdgKIb2L4PdDp2magZdRhnFyRyAe6NHHLd77169EGdgAlVY=
  on:
    branch: main
    python: 3.8
