language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

env:
  global:
    - OMP_NUM_THREADS=4
    - LINUX_DIST=trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"

before_install:
  - sudo apt-get update -yqq
install:
  - sudo apt install -yqq libtbb-dev
  - sudo apt -yqq install libgeos-dev
  - pip install --no-cache-dir cython wheel
  - pip install --no-cache-dir shapely==1.8a1 --no-binary shapely
  - pip install --no-cache-dir pygeos --no-binary pygeos
  - pip install --no-cache-dir -r requirements_test.txt
  - python setup.py install
  - cmake . --target capi_test
  - make
script:
  - ./capi_test
  - python run_tests.py